import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/styles/globals.css";
import NavBarHome from "@/components/Header/Navbar";
import NavBarAuth from "@/components/Header/NavBarAuth";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import { cookies } from "next/headers";

const inter = Inter({
  subsets: ["latin"],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Gammal Tech Exam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const isAuthenticated = cookieStore.get("isAuthenticated")?.value === "true";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}
      >
        {isAuthenticated ? <NavBarAuth /> : <NavBarHome />}
        {children}
        {/* {router.asPath !== '/lessons/result' && ( */}
        <Footer />
        {/* )} */}
      </body>
    </html>
  );
}
